# You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

# b[0] is equal to a[0];
# b[1] is equal to the last element of a;
# b[2] is equal to a[1];
# b[3] is equal to the second-last element of a;
# b[4] is equal to a[2];
# b[5] is equal to the third-last element of a;
# and so on.

def alternatingSort(a):
    b = [None for _ in range(len(a))]
    b[0] = a[0]
    tmp = 1
    for i in range(1,len(a)):
        if i%2==0:
           b[i] = a[tmp]
           tmp+=1
        else:
            b[i] = a[len(a)-tmp] 
    return b==sorted(b)

print(alternatingSort([-92, -23, 0, 45, 89, 96, 99, 95, 89, 41, -17, -48]))